package ca.uwaterloo.cs446.bighero6.util

import android.content.Context
import android.provider.Settings
import android.provider.Settings.Global.getString
import android.util.Log
import android.widget.Toast
import ca.uwaterloo.cs446.bighero6.repository.FirestoreRepository
import com.google.android.gms.tasks.OnCompleteListener
import com.google.firebase.firestore.auth.Token
import com.google.firebase.messaging.FirebaseMessaging
import com.google.firebase.auth.FirebaseAuth
import java.util.UUID

object DeviceIdManager {
    private const val PREFS_NAME = "taplist_prefs"
    private const val KEY_USER_ID = "user_id"
    private const val KEY_FCM_TOKEN = "fcm_token"
    private const val LOG_TAG = "DeviceIDManager"


    /**
     * Get the current user ID.
     * Prioritizes Firebase Auth UID if signed in.
     * Falls back to a locally stored UUID for guest access or legacy support.
     */
    fun getUserId(context: Context): String {
        val firebaseUser = FirebaseAuth.getInstance().currentUser
        if (firebaseUser != null) {
            return firebaseUser.uid
        }

        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val storedUserId = prefs.getString(KEY_USER_ID, null)

        if (storedUserId != null) return storedUserId

        // ONLY use UUID. Never touch ANDROID_ID.
        val newUserId = UUID.randomUUID().toString()
        prefs.edit().putString(KEY_USER_ID, newUserId).apply()
        return newUserId
    }

    /**
     * Only intended for saving the FCM token generated by the FCM SDK
     */
    fun saveFcmToken(context: Context, token: String)
    {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_FCM_TOKEN, token).apply()

        Log.d(LOG_TAG, "Saved FCM token in Device preferences for later reference: $token")

        // TODO if stored user already exists, update
        // We don't know when fcm token will be rotated so good to be safe

        val storedUserId = prefs.getString(KEY_USER_ID, null)
        if (storedUserId != null) {
            // we already have a user on the app and want to force update
            // FirestoreRepository.updateFcmToken
        }
    }

    fun getFcmToken(context: Context) : String?
    {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

        // Check if we already have a stored user ID
        val storedFCMToken : String? = prefs.getString(KEY_FCM_TOKEN, null)
        return storedFCMToken
    }

    /**
     * Reset user ID - generates a new UUID (for testing with multiple emulators)
     */
    fun resetUserId(context: Context): String {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val newUserId = UUID.randomUUID().toString()
        prefs.edit().putString(KEY_USER_ID, newUserId).apply()
        return newUserId
    }
}
