package ca.uwaterloo.cs446.bighero6.util

import android.content.Context
import android.provider.Settings
import android.provider.Settings.Global.getString
import android.util.Log
import android.widget.Toast
import ca.uwaterloo.cs446.bighero6.repository.FirestoreRepository
import com.google.android.gms.tasks.OnCompleteListener
import com.google.firebase.firestore.auth.Token
import com.google.firebase.messaging.FirebaseMessaging
import java.util.UUID

object DeviceIdManager {
    private const val PREFS_NAME = "taplist_prefs"
    private const val KEY_USER_ID = "user_id"
    private const val KEY_FCM_TOKEN = "fcm_token"
    private const val LOG_TAG = "DeviceIDManager"
    
    /**
     * Get or create a unique user ID for this device.
     * 
     * For emulators: Always uses UUID (each emulator instance gets a unique UUID)
     * For real devices: Uses Android ID if available, otherwise UUID
     * 
     * The ID is stored in SharedPreferences and persists across app restarts.
     * Each device/emulator instance will have a different ID by default.
     */
    fun getUserId(context: Context): String {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        
        // Check if we already have a stored user ID
        val storedUserId = prefs.getString(KEY_USER_ID, null)
        if (storedUserId != null) {
            return storedUserId
        }
        
        // Generate new user ID
        val androidId = Settings.Secure.getString(
            context.contentResolver,
            Settings.Secure.ANDROID_ID
        )
        
        // For emulators (which often share the same Android ID), always use UUID
        // This ensures each emulator instance gets a unique ID
        val userId = if (androidId != null && androidId != "9774d56d682e549c") {
            // Real device with unique Android ID
            androidId
        } else {
            // Emulator or device without Android ID - use UUID
            // Each emulator instance will generate a different UUID
            UUID.randomUUID().toString()
        }
        
        // Store for future use
        prefs.edit().putString(KEY_USER_ID, userId).apply()
        
        return userId
    }

    /**
     * Only intended for saving the FCM token generated by the FCM SDK
     */
    fun saveFcmToken(context: Context, token: String)
    {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        prefs.edit().putString(KEY_FCM_TOKEN, token).apply()

        Log.d(LOG_TAG, "Saved FCM token in Device preferences for later reference: $token")

        // TODO if stored user already exists, update
        // We don't know when fcm token will be rotated so good to be safe

        val storedUserId = prefs.getString(KEY_USER_ID, null)
        if (storedUserId != null) {
            // we already have a user on the app and want to force update
            // FirestoreRepository.updateFcmToken
        }
    }

    fun getFcmToken(context: Context) : String?
    {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)

        // Check if we already have a stored user ID
        val storedFCMToken : String? = prefs.getString(KEY_FCM_TOKEN, null)
        return storedFCMToken
    }

    /**
     * Reset user ID - generates a new UUID (for testing with multiple emulators)
     */
    fun resetUserId(context: Context): String {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val newUserId = UUID.randomUUID().toString()
        prefs.edit().putString(KEY_USER_ID, newUserId).apply()
        return newUserId
    }
}
